# Generated by Django 2.2 on 2020-02-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Borse'), ('A', 'Accessori')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'nuovo'), ('S', 'sconto'), ('C', 'normale')], max_length=1),
        ),
    ]
